apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: gatewayconfigs.mio.io
spec:
  group: mio.io
  version: v1alpha1
  names:
    kind: GatewayConfig
    plural: gatewayconfigs
  scope: Namespaced